//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistran.GestaoProduto.TokenServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/Sistran.ControleAcessosService")]
    [System.SerializableAttribute()]
    public partial class Token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataExpiracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataExpiracao {
            get {
                return this.DataExpiracaoField;
            }
            set {
                if ((this.DataExpiracaoField.Equals(value) != true)) {
                    this.DataExpiracaoField = value;
                    this.RaisePropertyChanged("DataExpiracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valido {
            get {
                return this.ValidoField;
            }
            set {
                if ((this.ValidoField.Equals(value) != true)) {
                    this.ValidoField = value;
                    this.RaisePropertyChanged("Valido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TokenServiceReference.ITokenService")]
    public interface ITokenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/GenerateToken", ReplyAction="http://tempuri.org/ITokenService/GenerateTokenResponse")]
        Sistran.GestaoProduto.TokenServiceReference.Token GenerateToken();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/GenerateToken", ReplyAction="http://tempuri.org/ITokenService/GenerateTokenResponse")]
        System.Threading.Tasks.Task<Sistran.GestaoProduto.TokenServiceReference.Token> GenerateTokenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/ValidateToken", ReplyAction="http://tempuri.org/ITokenService/ValidateTokenResponse")]
        bool ValidateToken(System.Guid token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/ValidateToken", ReplyAction="http://tempuri.org/ITokenService/ValidateTokenResponse")]
        System.Threading.Tasks.Task<bool> ValidateTokenAsync(System.Guid token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenServiceChannel : Sistran.GestaoProduto.TokenServiceReference.ITokenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenServiceClient : System.ServiceModel.ClientBase<Sistran.GestaoProduto.TokenServiceReference.ITokenService>, Sistran.GestaoProduto.TokenServiceReference.ITokenService {
        
        public TokenServiceClient() {
        }
        
        public TokenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sistran.GestaoProduto.TokenServiceReference.Token GenerateToken() {
            return base.Channel.GenerateToken();
        }
        
        public System.Threading.Tasks.Task<Sistran.GestaoProduto.TokenServiceReference.Token> GenerateTokenAsync() {
            return base.Channel.GenerateTokenAsync();
        }
        
        public bool ValidateToken(System.Guid token) {
            return base.Channel.ValidateToken(token);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateTokenAsync(System.Guid token) {
            return base.Channel.ValidateTokenAsync(token);
        }
    }
}
